// import Head from 'next/head'
import Navbar from './Navbar'
import Script from 'next/script';
// import Footer from './footer'
import { useEffect, useState } from 'react';
import Head from 'next/head';
import Footer from './Footer';



export default function Layout(props) {

  const [getUser, setUser] = useState('');

  return (
    <>
      <Head>
        <title>DigiCruiter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <Navbar />
        {props.children}
      <Footer/>
    </>
  )
}
